airline/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('flights/', include("flight.urls")),
    path("users/", include("users.urls"))

]

flight/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'flight'
urlpatterns = [
    path('',views.index, name='index'),
    path("<int:flight_id>", views.flights, name='flights'),
    path("<int:flight_id>/book", views.book, name='book')

]

users/urls.py
from django.urls import path
from . import views



urlpatterns =[
    path("", views.index, name='index'),

    path("login/", views.login_view, name='login'),

    path("logout/", views.logout_view, name='logout')

]

flight/models.py
from django.db import models

# Create your models here.

class Airport(models.Model):
    code = models.CharField(max_length=3)
    city = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.city} ({self.code})"

class Flight(models.Model):
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name='departures')
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name='arrivals')
    duration = models.IntegerField()

    def __str__(self):
        return f"{self.id} : {self.origin} to {self.destination}"

    def is_valid_flight(self):
        return self.origin!=self.destination or self.duration>=0

class Passenger(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    flights = models.ManyToManyField(Flight, blank=True, related_name='passengers')

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

users/models.py
from django.db import models

# Create your models here.

flight/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .models import Flight,Passenger
from django.urls import reverse


# Create your views here.

def index(request):
    flights =Flight.objects.all()
    return render(request, 'flight/index.html',{'flights':flights})

def flights(request, flight_id):
    flights = Flight.objects.get(pk=flight_id)
    
    return render(request, 'flight/flights.html',{
        'flight':flights,
        'passengers':flights.passengers.all(),
        'non_passenger':Passenger.objects.exclude(flights=flights).all()
         

        })

def book(request, flight_id):
       
        if request.method=="POST":
            flight = Flight.objects.get(pk=flight_id)
    
            passenger =Passenger.objects.get(pk=int(request.POST['passengers']))
        
            passenger.flights.add(flight)

            return HttpResponseRedirect(reverse('flight:flights',args=(flight.id,)))

users/views.py
from django.contrib.auth import authenticate,login,logout
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse


def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('login'))
    return render(request, 'users/user.html')

def login_view(request):

    if request.method=="POST":
        username = request.POST["username"]
        password = request.POST['password']
        user = authenticate(request, username = username,password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, 'users/login.html',{
                'message':'invalid credentials.'
            })


    return render(request, 'users/login.html')

def logout_view(request):
    logout(request)
    return render(request, 'users/logout.html',{
        "message": "Logged out successfully"

    })
    

flight/templates/flight/flights.html
{% extends 'flight/layout.html' %}

{% block body %}
    <h1>Flight{{flight.id}}</h1>
    <ul>
        <li>Origin : {{flight.origin}}</li>
        <li>Destination : {{flight.destination}}</li>
        <li>Duration : {{flight.duration}}</li>
    </ul>
    <h1>Passenger</h1>
    <ul>
        {% for passenger in passengers %}
        <li>{{passenger}}</li>
        {% empty %}
        <h3>No Passenger</h3>
        
        {% endfor %}
    </ul>
    
    <h2>Add passenger</h2>
    
    
    <form action="{% url 'flight:book' flight.id %} " method="POST">
        {% csrf_token %}
        <select name="passengers">
        {% for passenger in non_passenger %}
        <option value="{{passenger.id}}">{{passenger}}</option>
        {% endfor %}
    </select>
    <input type='submit'>

    </form>

    <h2><a href="{% url 'flight:index'%}">Back Flight list</a></h2>
{% endblock %}

flight/templates/flight/index.html
    {% extends 'flight/layout.html' %}


    {% block body %}
    <h1>Flight list : </h1>

            {%for flight in flights %}
            <ul>   
                <h3><a href="{% url 'flight:flights' flight.id %}">{{flight.id}}: {{flight.origin}} to {{flight.destination}}</a> </h3>
               
            </ul>
        
            {% endfor %}

        {% endblock %}

       
    </body>
</html>

flight/templates/flight/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>layout</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

users/templates/users/index.html
{% extends 'users/layout.html' %}
{%block body %}
<h1>index page</h1>
{% endblock %}

users/templates/users/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>User</title>

    </head>

    <body>
        {% block body %}

        {% endblock %}

    </body>
</html>

users/templates/users/login.html
{% extends 'users/layout.html' %}

{% block body %}
{% if message %}
<div><h1>{{message}}</h1>
    <h3>please enter correct username and password</h3>
</div>
{% endif %}

<form action="{% url 'login' %}" method="POST">
    {% csrf_token %}

    <label for="username">Username </label>
    <input type="text" id="username" name="username" placeholder="username">
    <br><br>
    <label for="password">Password </label>
    <input type="password" id="password" name="password" placeholder="password"><br>
            
    <input  type="submit" value="Login">

</form>
{% endblock %}

users/templates/users/logout.html
{% extends 'users/layout.html' %}

{% block body %}
{% if message %}
<div>{{message}}</div>
{% endif %}
<h1 ><a href="{% url 'login' %}">Login Again</a></h1>
{% endblock %}

users/templates/users/user.html
{% extends 'users/layout.html' %}
{% block body %}
    <h1>Welcom {{request.user.first_name}}</h1>
    <ul>
        <li>Name: {{request.user.username}}</li>
        <li>Email: {{request.user.email}}</li>
    </ul>
    <a href="{% url 'logout' %}">Log out</a>

{% endblock %}